FakeCSV/urls.py
from django.contrib import admin
from django.urls import path
from csvgen.views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("", HomeView.as_view(), name="home"),
    path("new/", NewView.as_view(), name="new"),
    path("edit/<int:id>/", EditView.as_view(), name="edit"),
    path("logout/", logout_view, name="logout"),
    path("add/", AddSchemaFormView.as_view(), name="add_schema"),
    path("create/", CreateCsvView.as_view(), name="create"),
    path("download/<str:filename>/", CsvDownload.as_view(), name="download"),
    path("delete_schema/<int:id>/", DeleteSchema.as_view(), name="delete_schema"),
]

csvgen/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Schemas(models.Model):
    title = models.CharField(max_length=50)
    Column_separator = models.CharField(max_length=50, default="Comma (,)")
    String_character = models.CharField(max_length=50, default='Double-quote (")')
    Post_date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    fields = models.TextField(default="[()]")
    # Fields syntax (<name of field>, <type of field>, <from>, <to>, <sentences>)
    # from/to/sentences can be None


class CsvFile(models.Model):
    filename = models.CharField(max_length=50)  # example 5_20.csv\10_100.csv
    create_date = models.DateField()
    schema_id = models.IntegerField()
    is_ready = models.BooleanField()

csvgen/forms.py
from django import forms


class AddForm(forms.Form):
    """Form for adding columns to ur schemas"""
    types = [
        ("date", "date"),
        ("integer", "integer"),
        ("phone", "phone"),
        ("email", "email"),
        ("name", "name"),
        ("address", "address"),
        ("domain", "domain"),
        ("job", "job"),
        ("company", "company"),
        ("text", "text"),
    ]
    Column_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class": "form-control"}))
    Type = forms.ChoiceField(choices=types, widget=forms.Select(attrs={"class": "form-control","id": "inputState"}))
    From = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}), required=False)
    To = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}), required=False)
    Sentences = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}), required=False)
    Order = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}))


class FullAddForm(forms.Form):
    """Form to add ur schema to DB"""
    Name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class": "form-control"}))
    Column_separator = forms.ChoiceField(choices=([("Comma (,)", "Comma (,)")]),
                                         widget=forms.Select(attrs={"class": "form-control","id": "inputState"}))
    String_character = forms.ChoiceField(choices=([('Double-quote (")', 'Double-quote (")')]),
                                         widget=forms.Select(attrs={"class": "form-control", "id": "inputState"}))


class RowForm(forms.Form):
    row = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}))
    num = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}))

csvgen/views.py
from django.shortcuts import render
import csv
from django.http import HttpResponse, HttpResponsePermanentRedirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from .models import Schemas, CsvFile
from .fakegen import *
from datetime import datetime
from .forms import AddForm, FullAddForm, RowForm
from .tasks import csv_generator
from wsgiref.util import FileWrapper
import os
from FakeCSV.settings import BASE_DIR

def logout_view(request):
    """Log out and redirect to home(log in form)"""
    logout(request)
    return HttpResponsePermanentRedirect("/")


class HomeView(LoginRequiredMixin, ListView):
    """Home page with user schemas list"""
    model = Schemas

    def get_queryset(self):
        """admin can see all schemas, user only his own"""
        if self.request.user.is_staff:
            return Schemas.objects.all()
        else:
            return Schemas.objects.filter(user=self.request.user)


class NewView(LoginRequiredMixin, View):
    """New Schema page"""
    add_list = list()


    def post(self, request):
        """Rendering with new columns"""
        print(request.POST, "POST")
        form = AddForm(request.POST)
        if form.is_valid():
            add_data = request.POST
            self.add_list.append(form)
            print(self.add_list, "LIST")
            return render(request, "csvgen/schemas_form.html", {"form": AddForm,
                                                                'list': self.add_list,
                                                                'form2': FullAddForm})
        else:
            return HttpResponse("form not valid")


    def get(self, request):
        """render page with forms"""
        self.add_list.clear()
        data = {"form": AddForm, "form2": FullAddForm}
        return render(request, "csvgen/schemas_form.html", context=data)

    def delete(self, request):
        print("DELETE")


class AddSchemaFormView(LoginRequiredMixin, View):

    def post(self, request):
        """Creating new schema and redirect to homepage"""
        # print(request.POST, "POST ADD")
        data = dict(request.POST)
        fields = []

        ints = []
        texts = []

        index1 = 0
        index2 = 0
        # creating tuples (<index of integer type>, <it from\to values index>)
        # Example >> 'Type': ['date', 'date', 'integer', 'phone', 'integer'],
        # 'Order': ['0', '1', '2', '3', '4'], 'From': ['1', '1'], 'To': ['2', '3']}
        # will be [(2, 0), (5, 1)]
        for i in range(len(data["Type"])):
            if data["Type"][i] == "integer":
                ints.append((i, index1))
                index1 += 1
            if data["Type"][i] == "text":
                texts.append((i, index2))
                index2 += 1
        # creating model Schemas and add to DB
        for i in range(len(data["Column_name"])):
            if "integer" == data["Type"][i]:
                for tuples in ints:
                    print(tuples, "_", i)
                    if tuples[0] == i:
                        int_index = tuples[1]
                print(ints)
                tmp = (data["Column_name"][i], data["Type"][i], data.get("From")[int_index],
                       data.get("To")[int_index], None, data["Order"][i])
            elif "text" == data["Type"][i]:
                for tuples in texts:
                    if tuples[0] == i:
                        txt_index = tuples[1]
                tmp = (data["Column_name"][i], data["Type"][i], None,
                       None, data.get("Sentences")[txt_index], data["Order"][i])
            else:
                tmp = (data["Column_name"][i], data["Type"][i], None,
                       None, None, data["Order"][i])
            fields.append(tmp)
        schema = Schemas(title=request.POST["Name"],
                         Post_date=datetime.now().date(),
                         user=self.request.user,
                         fields=str(fields))
        schema.save()
        return HttpResponsePermanentRedirect("/")


class EditView(LoginRequiredMixin, View):


    def get(self, request, id, *args, **kwargs):
        csvs = CsvFile.objects.filter(schema_id=id)
        return render(request, "edit_schema.html", {'form': RowForm, "id": id, "csvs": csvs})



class CreateCsvView(LoginRequiredMixin, View):

    def post(self, request):
        rows = int(request.POST["row"])
        id = request.META.get("HTTP_REFERER")
        id = id.split("/")[-2]

        # starting celery task
        csv_generator.delay(rows, id)
        filename = str(id) + "_" + str(rows) + '.csv'
        to_save = CsvFile(filename=filename, create_date=datetime.now().date(), schema_id=id, is_ready=0)
        to_save.save()
        return HttpResponsePermanentRedirect("/edit/" + id + "/")


class CsvDownload(LoginRequiredMixin, View):

    def get(self, request, filename):
        file_path = os.path.join(BASE_DIR, filename)
        if os.path.exists(file_path):
            with open(file_path, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type='text/csv')
                response['Content-Disposition'] = 'inline; filename=' + file_path
                return response


class DeleteSchema(LoginRequiredMixin, View):

    def get(self, request, id):
        Schemas.objects.get(pk=id).delete()
        return HttpResponsePermanentRedirect("/")

templates/csvgen/schemas_form.html
{% extends 'index.html' %}
{% load static %}
{% block title %}New{% endblock title %}
{% block links %}
<link href="{% static 'css/new.css' %}" rel="stylesheet">
{% endblock links %}
{% block content %}
<table class="table table-borderless">
    <thead>
      <tr>
        <th scope="col"><h2>Data schemas</h2></th>
        <th scope="col" id="button-table"><input type="submit" class="btn btn-primary" value="Submit" form="SchemaForm"></th>
      </tr>
    </thead>
</table>

<form method="POST" action="/add/" id="SchemaForm">
    {% csrf_token %}
    <div class="form-group form-groupcss">
      <label for="id_Name">Name</label>
      {{ form2.Name }}
    </div>
    <div class="form-group form-groupcss">
      <label for="id_Column_separator">Column separator</label>
      {{ form2.Column_separator }}
    </div>
    <div class="form-group form-groupcss">
        <label for="id_String_character">String character</label>
        {{ form2.String_character }}
    </div>
    <table class="table table-borderless">
    <thead>
        <tr>
            <th scope="col">Column name</th>
            <th scope="col">Type</th>
            <th scope="col">From</th>
            <th scope="col">To</th>
            <th scope="col">Sentences</th>
            <th scope="col">Order</th>
        </tr>
    </thead>
    <tbody>
    {% for element in list %}
        <tr>
            <th scope="col">{{ element.Column_name }}</th>
            <th scope="col">{{ element.Type }}</th>
            {% if element.Type.value == "integer" %}
            <th scope="col">{{ element.From }}</th>
            {% else %}
            <th scope="col"></th>
            {% endif %}
            {% if element.Type.value == "integer" %}
            <th scope="col">{{ element.To }}</th>
            {% else %}
            <th scope="col"></th>
            {% endif %}
            {% if element.Type.value == "text" %}
            <th scope="col">{{ element.Sentences }}</th>
            {% else %}
            <th scope="col"></th>
            {% endif %}
            <th scope="col">{{ element.Order }}</th>
        </tr>
    {% endfor %}
    </form>
    </tbody>
    </table>

  <form class="addform" method="POST" action="/new/">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-2">
          <label for="id_Column_name">Column name</label>
          {{ form.Column_name }}
        </div>
        <div class="form-group col-md-2">
          <label for="id_Type">Type</label>
          {{ form.Type }}
        </div>
        <div class="form-group col-md-1 type-input-int">
            <label for="id_From">From</label>
            {{ form.From }}
            <label for="id_To">To</label>
            {{ form.To }}
        </div>
        <div class="form-group col-md-1 type-input-txt">
            <label for="id_From">Count of sentences</label>
            {{ form.Sentences }}
          </div>
        <div class="form-group col-md-2">
          <label for="id_Order">Order</label>
          {{ form.Order }}
        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="ADD">
  </form>
{% endblock content %}
{% block script %}
<script>

  document.querySelector('#inputState').addEventListener('input', (e) => {
        if (e.target.value === 'integer'){
            document.querySelectorAll('.type-input-int').forEach(input => {
            input.style.display = 'block'
        })
        }
        else if (e.target.value === 'text'){
            document.querySelectorAll('.type-input-txt').forEach(input => {
            input.style.display = 'block'
        })
        }
    })
</script>
{% endblock script %}

templates/csvgen/schemas_list.html
{% extends 'index.html' %}
{% load static %}
{% block links %}
<link href="{% static 'css/list.css' %}" rel="stylesheet">
{% endblock links %}


{% block content %}
<table class="table table-borderless">
    <thead>
      <tr>
        <th scope="col"><h2>Data schemas</h2></th>
        <th scope="col" id="button-table"><button type="button" class="btn btn-success" ><a href="{% url 'new' %}" style="color: white;">New Schema</a></button></th>
      </tr>
    </thead>
</table>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td scope="col">#</td>
                <td scope="col">Title</td>
                <td scope="col">Modified</td>
                <td scope="col">Actions</td>
            </tr>
        </thead>
        <tbody>
    {% for schema in object_list %}
        <tr>
            <td scope="row">{{ schema.pk }}</td>
            <td><a href="{% url 'edit' schema.pk %}">{{ schema.title }}</a></td>
            <td>{{ schema.Post_date|date }}</td>
            <td><a href="{% url 'edit' schema.pk %}">Edit</a><a href="{% url 'delete_schema' schema.pk%}" style="color: red;">Delete</a></td>
        </tr>
        
    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}
        </tbody>
    </table>
{% endblock content %}